### PR TITLE
Enable sse2/avx2 if available

### PR DESCRIPTION
**Pull request by mulimoen**

### CODE REVIEW

**Comment by mulimoen** [comment]
@LDeakin Does this PR work for you in getting the intrinsics version of shuffles? This requires `RUSTFLAGS=-C target-feature=+avx2,+sse2` and will not be set automatically as it would in `CMake`

**Comment by LDeakin** [comment]
Yes, that does the trick! Although, I don't even need to set `RUSTFLAGS=-C target-feature=+avx2,+sse2`.

**Comment by LDeakin** [comment]
Update: with `RUSTFLAGS="-C target-feature=+avx2,+sse2"`, I get a crash. This does not occur on the main branch, so this seems like an issue with `blosc-c`.

**Comment by mulimoen** [comment]
Yeah, I see the crash when using `avx2`, I will fix this

**Comment by LDeakin** [comment]
You probably need these compile definitions https://github.com/Blosc/c-blosc/blob/bdbb700787a2485a756eea63ced268f9a00f6370/blosc/CMakeLists.txt#L157-L192

**Comment by mulimoen** [comment]
Need to pass these flags to `cc` as this is not done automatically, https://github.com/rust-lang/cc-rs/issues/268. I'll see what I can do tomorrow

**Comment by LDeakin** [comment]
https://github.com/mulimoen/rust-blosc-src/pull/7/commits/3290ebd04efdadae7be5b413835b5e3a46b1bd8f works and I've tested it with a suite of external benchmarks, LGTM.

**Comment by mulimoen** [comment]
Thanks for picking up that this crate did not use SSE2/AVX @LDeakin. I will release a new version later today

**Comment by LDeakin** [comment]
No worries, thanks for addressing it so quickly!

**Pull request merged**
