### PR TITLE
Fix target_* usage in the build script

### LINKED ISSUE #14: Cross compilation is broken
I'm trying to cross compile a larger application from linux (x86_64) to linux (aarch64) that depends on blosc-src. I get the following error:

```
The following warnings were emitted during compilation:

warning: blosc-src@0.3.1: aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-msse2’

error: failed to run custom build command for `blosc-src v0.3.1`

Caused by:
  process didn't exit successfully: `/tmp/test_blosc/target/debug/build/blosc-src-8213a8b070384c50/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=build.rs
  TARGET = Some("aarch64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_aarch64-unknown-linux-gnu
  CC_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_aarch64_unknown_linux_gnu
  CC_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = None
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-unknown-linux-gnu
  CFLAGS_aarch64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_unknown_linux_gnu
  CFLAGS_aarch64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-msse2’
```

From looking at the relevant source code the problem seems to be this part:

https://github.com/mulimoen/rust-blosc-src/blob/0bdc02191eb236f0f8b6639ca23f3a3132a57102/build.rs#L24-L41

It uses the `cfg!` macro which is evaluated at compile time and therefore refers to the host target_features in this case. Instead the script needs to read and evaluate the `CARGO_CFG_TARGET_FEATURE` set by [cargo for build scripts](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

(There is another issue with the build script with the `cfg!(target_env = "msvc")` a few lines above that can be resolved in a similar way).

### PR DESCRIPTION
**Pull request by weiznich**
This commit replaces the usage of `cfg!(target_*)` with `std::env::var` to read the correct values of these configs from the environment set by cargo rather than using the configs of the host system.

Fixes #14

### CODE REVIEW

**Comment by weiznich** [comment]
I've filled https://github.com/rust-lang/rust/issues/125441 for that as that happened a few times for me as well and I also noticed this in other crates as well.

**Comment by mulimoen** [comment]
Thanks for the issue, fix and the follow-up with the rust team. I'll publish a new version of this crate when I am back at a computer

**Comment by weiznich** [comment]
No worries and take your time for publishing the release. I'm fine with just using an entry in `[patch.crates-io]` for now.

**Comment by mulimoen** [comment]
`blosc-src = "0.3.2"` is not available

**Pull request merged**
